[Tensor shape 변경]

In [4]:
## 모듈로딩
import torch

OSError: [WinError 126] 지정된 모듈을 찾을 수 없습니다. Error loading "c:\Users\KDP-35\anaconda3\envs\DL_TORCH\lib\site-packages\torch\lib\cudnn_adv64_9.dll" or one of its dependencies.

In [49]:
import torch
print("PyTorch 버전:", torch.__version__)
print("CUDA 지원 버전:", torch.version.cuda)
print("CUDA 사용 가능:", torch.cuda.is_available())



PyTorch 버전: 2.4.0
CUDA 지원 버전: None
CUDA 사용 가능: False


In [50]:
import torch
print("PyTorch 버전:", torch.__version__)
print("CUDA 지원 버전:", torch.version.cuda)
print("CUDA 사용 가능:", torch.cuda.is_available())
print("사용 중인 GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "GPU 사용 불가")


PyTorch 버전: 2.4.0
CUDA 지원 버전: None
CUDA 사용 가능: False
사용 중인 GPU: GPU 사용 불가


In [66]:
## 텐서 생성
t1 = torch.tensor([11,22,33,44,55,66])

In [52]:
## shape 변경 => reshape()-----------------------------------
t2 = t1.reshape(-1,1,1)	# 1D => 3D
t2.shape

torch.Size([6, 1, 1])

In [53]:
## t1 1D ==> 4D, t3 저장하기
t3 = t1.reshape(-1,1,1,1)
t3.shape

torch.Size([6, 1, 1, 1])

In [54]:
## shape 변경 => view()---------------------------------------
t2 = t1.view(2, 3)
t2.shape

torch.Size([2, 3])

In [55]:
t3 = t1.view(-1, 2, 3)
t3.shape

torch.Size([1, 2, 3])

##### [ Axis 변경]

- axis란?
	* Tensor의 shape 정보에서 확인
	* 2D => (m, n) => axis0 m, axis1 n
	* 3D => (l, m, n) => axis0 l, axis1 m, axis2 n

In [56]:
### transpose() 메서드 ============================
t1 = torch.tensor([[11, 22, 33], [33, 44, 55]])
t2 = torch.tensor([[[11, 22, 33], [33, 44, 55]]])
print( t1.shape, t1, sep='\n')
print( t2.shape, t2, sep='\n')

torch.Size([2, 3])
tensor([[11, 22, 33],
        [33, 44, 55]])
torch.Size([1, 2, 3])
tensor([[[11, 22, 33],
         [33, 44, 55]]])


In [57]:
## 0번 축 <-> 1번 축
print( t1.shape, t1, sep='\n')
t1.transpose(1, 0)

torch.Size([2, 3])
tensor([[11, 22, 33],
        [33, 44, 55]])


tensor([[11, 33],
        [22, 44],
        [33, 55]])

In [58]:
## 0번 축 <-> 1번 축
print( t2.shape, t2, end='\n\n')

t3 = t2.transpose(1, 0)
print( t3.shape, t3, end='\n\n')

## 0번 축 <-> 2번 축 (1, 2, 3) ==> (3, 2, 1)
t4 = t2.transpose(2, 0)
print( t4.shape, t4, end='\n\n')

torch.Size([1, 2, 3]) tensor([[[11, 22, 33],
         [33, 44, 55]]])

torch.Size([2, 1, 3]) tensor([[[11, 22, 33]],

        [[33, 44, 55]]])

torch.Size([3, 2, 1]) tensor([[[11],
         [33]],

        [[22],
         [44]],

        [[33],
         [55]]])



In [59]:
## - 모든 축 axis 변경 가능
t2 = torch.tensor([[[11, 22, 33], [33, 44, 55]]])
print( t2.shape, t2, sep='\n')

torch.Size([1, 2, 3])
tensor([[[11, 22, 33],
         [33, 44, 55]]])


In [60]:
## (1,2,3) ==> (2,3,1)
t3 = t2.permute(1,2,0)
print(t3.shape, t3, sep='\n')

torch.Size([2, 3, 1])
tensor([[[11],
         [22],
         [33]],

        [[33],
         [44],
         [55]]])


- 차원 줄이기 단, 원소 갯수 유지

In [61]:
# 이미지 1장 => 가로, 세로 5, 흑백 1 
# - 형태 : (5, 5, 1)
# - 원소: 5 * 5 *1 = 25
t1 = torch.arange(11, 36)
t1.shape

torch.Size([25])

In [62]:
t2=t1.reshape(5,5,1)
t2.shape

torch.Size([5, 5, 1])

In [63]:
## 채널을 제일 앞으로 보내기
t3=t2.transpose(0, 2)
t3.shape

torch.Size([1, 5, 5])

In [64]:
## 원소 갯수 유지하면서 3D ==> 2D
t4=t3.squeeze()
t4.shape

torch.Size([5, 5])

In [65]:
## 원소 갯수 유지하면서 2D ==> 3D
t4.unsqueeze(1).shape

torch.Size([5, 1, 5])