[ Tensor 생성 및 속성 확인 ]

[1] 모듈 로딩 <hr>

In [25]:
import torch		## 텐서 및 공통 함수들 모듈
import utils		## 사용자 정의 함수들 모듈
import numpy as np

[2] 텐서 생성 및 속성 확인 <hr>

In [7]:
# 임의의 값으로 텐서 생성
torch.manual_seed(12)

In [8]:
t1 = torch.rand(2,3)			# [0, 1) 분포 안에서 램덤 생성
t2 = torch.randn(2,3)			# standard normal 분포 안에서 랜덤 생성

t3 = torch.randint(low=1,high=10,size=(2,3)) # [low, high] low<=값<high

In [9]:
## 텐서 속성 확인
utils.printTensorInfo('t1', t1)

t1-----------------------------
shape  : torch.Size([2, 3])	 torch.Size([2, 3])
ndim   : 2      2
device : cpu
dtype  : torch.float32
tensor : tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])


In [10]:
## 텐서 속성 확인
utils.printTensorInfo('t3', t3)

t3-----------------------------
shape  : torch.Size([2, 3])	 torch.Size([2, 3])
ndim   : 2      2
device : cpu
dtype  : torch.int64
tensor : tensor([[8, 4, 6],
        [2, 2, 2]])


In [11]:
## 생성 - Numpy 객체로 값 채운 Tensor
arr = np.linspace(1,10,6)			# ndarray 객체

In [12]:
## ndarray ==> tensor 생성
t1 = torch.from_numpy(arr)			# share방식 => 원본 공유, 변경 시 함께 변경
t2 = torch.as_tensor(arr)			# share방식 => 원본 공유, 변경 시 함께 변경
t3 = torch.tensor(arr)				# copy방식  => 새로운 메모리 공간에 데이터 복사

In [13]:
## 체크 !!
print(f'[전] arr => {arr}')
arr[0]=5.0
print(f'[후] arr => {arr}')

[전] arr => [ 1.   2.8  4.6  6.4  8.2 10. ]
[후] arr => [ 5.   2.8  4.6  6.4  8.2 10. ]


In [14]:
## 텐서 체크
print('t1 =>', t1)
print('t2=> ', t2)
print('t3 =>', t3)

t1 => tensor([ 5.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)
t2=>  tensor([ 5.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)
t3 => tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)


In [15]:
## tensor 데이터 ==> tensor 생성
t0 = torch.tensor([11,22])

#t1 = torch.from_numpy(t0)			# share방식 => 원본 공유, 변경 시 함께 변경
t2 = torch.as_tensor(t0)			# share방식 => 원본 공유, 변경 시 함께 변경
t3 = torch.tensor(t0)				# copy방식  => 새로운 메모리 공간에 데이터 복사

C:\Users\KDP-35\AppData\Local\Temp\ipykernel_7220\2550043006.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t3 = torch.tensor(t0)				# copy방식  => 새로운 메모리 공간에 데이터 복사


In [16]:
## 텐서 원소 변경
print( t0[0], t0[1] )
print( t0[0].item(), t0[1].item() )

tensor(11) tensor(22)
11 22


In [17]:
t0[0] = 9
print( t0[0].item(), t0[1].item() )

9 22


In [18]:
# as_tensor() share로 원본 변경 시 적용 O
# tensor() copy로 원본 변겅 시 적용 X
print(t2, t3)

tensor([ 9, 22]) tensor([11, 22])


[4] 특정 데이터타입의 Tensor 생성 <hr>

In [19]:
t1 = torch.FloatTensor([11,0])
print(t1, t1.type, sep='\n')

tensor([11.,  0.])
<built-in method type of Tensor object at 0x000001E21C820040>


In [20]:
t1 = torch.DoubleTensor([11,0])
print(t1, t1.type, sep='\n')

tensor([11.,  0.], dtype=torch.float64)
<built-in method type of Tensor object at 0x000001E21C8201D0>


In [21]:
t1 = torch.BoolTensor([11,0])
print(t1, t1.type, sep='\n')

tensor([ True, False])
<built-in method type of Tensor object at 0x000001E21C820AE0>
