[Tensor Indexing & Slicing]

In [3]:
## 모듈 로딩
import torch
import numpy as np

In [4]:
## 텐서 생성
t1 = torch.linspace(1, 10, 6)
t1

tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000])

In [5]:
## 인덱싱
t1[0], t1[-1]

(tensor(1.), tensor(10.))

In [6]:
## 여러개 원소 읽기
t1[[0, -1]]

tensor([ 1., 10.])

In [7]:
## 슬라이싱
t1[:-1]

tensor([1.0000, 2.8000, 4.6000, 6.4000, 8.2000])

#### [ Tensor 연산 - 브로드캐스팅]

In [8]:
# Case1: 같은 크기 행렬
m1 = torch.FloatTensor([[3, 4]])
m2 = torch.FloatTensor([[2, 5]])

In [9]:
m3 = m1+m2

In [10]:
print(m3, m3.shape)

tensor([[5., 9.]]) torch.Size([1, 2])


In [11]:
#Case 2 : 벡터와 행렬
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])

In [12]:
m3 = m1+m2

In [13]:
print(m3, m3.shape)

tensor([[4., 5.]]) torch.Size([1, 2])


In [14]:
# Case 3 : 크기 다른 두 개 행렬
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])

In [15]:
m3 = m1+m2

In [16]:
print(m3, m3.shape)

tensor([[4., 5.],
        [5., 6.]]) torch.Size([2, 2])


#### [ Tensor 연산 - 행렬 곱셈 matmul()]

In [17]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [18]:
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])


In [19]:
m12 = m1.matmul( m2 )
print( m12.shape)

torch.Size([2, 1])


#### [view() 메서드] 

In [20]:
t2 = torch.tensor([[1,2,3,], [4,54,56]])
print(t2.shape)

torch.Size([2, 3])


In [21]:
t2.view(3,2)
print( t2.shape )

torch.Size([2, 3])
